import { RegisterClass } from "@/classes/utility/JsonHelper";
import { WorldNode } from "./WorldNode";
import { makeAutoObservable } from "mobx";

@RegisterClass
export class Story {
    public name: string = "";
    public description: string = "";
    public nodesList: WorldNode[] = [];
    private nodesDictionary: { [key: string]: WorldNode } = {};

    private nodeParent: { [key: string]: string } = {};
    private nodeChildren: { [key: string]: WorldNode[] } = {};

    constructor(name: string, description: string) {
        this.name = name;
        this.description = description;
        makeAutoObservable(this);
    }

    /**
     * Replaces all occurences of the node and children's names in the text with a colored version of the name.
     * Also shows the renderer who the node is.
     * @param text The text to replace the names in.
     */
    public markNodesInText(text: string): string {
        const plausibleObjects = this.getContextNodes(this.nodesDictionary["player"]);

        for (const object of plausibleObjects) {
            text = text.replace(new RegExp(`\\b(${object.name.toLowerCase()})\\b`, "gmi"), `[node;${object.id};[color;${object.color};$1]]`);
        }

        return text;
    }

    public getSiblings(node: WorldNode | null): WorldNode[] {
        return this.getChildNodes(this.getParentNode(node))
                   .filter(n => n.id !== node?.id);
    }

    public getChildNodes(node: WorldNode | null): WorldNode[] {
        return this.nodeChildren[node?.id ?? ""] || [];
    }

    public getParentNode(node: WorldNode | null): WorldNode | null {
        const nodeId = node?.id ?? "";
        return this.nodeParent[nodeId] ? this.nodesDictionary[this.nodeParent[nodeId]] : null;
    }

    public getContextNodes(node: WorldNode): WorldNode[] {
        const contextNodes = [...this.getSiblings(node),
                              ...this.getChildNodes(node),
                              node];

        if (this.getParentNode(node)) {
            contextNodes.push(this.getParentNode(node)!);
        }

        return contextNodes;
    }

    public performActionAsync(actionText: string): Promise<void> {
        const contextNodes = this.getContextNodes(this.nodesDictionary["player"]);
        return this.nodesDictionary["player"].performActionAsync(actionText, contextNodes);
    }

    public removeNode(node: WorldNode): void {
        this.nodesList = this.nodesList.filter(n => n.id !== node.id);
        delete this.nodesDictionary[node.id];
    }

    public addNode(node: WorldNode): void {
        this.nodesList.push(node);

        if (!node.id)
            node.id = this.generateId(node.name);

        // ToDo: Sort the list by x coordinate for easier spatial reasoning. But do it better.
        // this.nodesList.sort((a, b) => a.coordinates.x - b.coordinates.x);

        this.nodesDictionary[node.id] = node;
    }

    public getDictionary(): { [key: string]: WorldNode } {
        return this.nodesDictionary;
    }

    public fillDictionary(): void {
        this.nodesDictionary = {};
        this.nodesList.forEach(node => {
            this.nodesDictionary[node.id] = node;
        });

        const sortedNodes = this.nodesList.slice().sort((a, b) => {
            return a.getVolume() - b.getVolume();
        });

        // Create a hierarchical structure based on containment.
        for (let i = 0; i < sortedNodes.length; i++) {
            const node = sortedNodes[i];
            let parentNodeId = "";

            for (let j = i - 1; j >= 0; j--) {
                const potentialParent = sortedNodes[j];

                if (node.isInside(potentialParent, false)) {
                    parentNodeId = potentialParent.id;
                    break;
                }
            }

            this.nodeChildren[parentNodeId] = this.nodeChildren[parentNodeId] || [];
            this.nodeChildren[parentNodeId].push(node);
            this.nodeParent[node.id] = parentNodeId;
        }
    }

    /**
     * Generates a unique id not yet taken by another node.
     * @returns A unique id for the node. This is generated by normalizing the name and appending an iterative number if the id already exists.
     */
    public generateId(name: string): string {
        const genName: string = name.replace(/[^a-zA-Z0-9]/g, "_").toLowerCase();
        let genNumber: number = 0;
        let genId = genName;

        while (genId in this.nodesDictionary) {
            genId = `${genName}_${++genNumber}`;
        }

        return genId;
    }
}
